language: python
python:
 - "2.6"
 - "2.7"
env:
 - DJANGO_VERSION=1.5.1
 - DJANGO_VERSION=1.6.7
install:
 - pip install -r requirements.txt
 - pip install -q django==$DJANGO_VERSION
script:
 - pep8 --exclude=migrations table_stacker
 - flake8 --exclude=migrations table_stacker
 - python manage.py syncdb --noinput
 - python manage.py migrate
 - python manage.py build
 - coverage run manage.py test table_stacker
after_success:
 - coveralls
